import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import * as T from '../vendor/three.module.js';import {rigMawhound} from '../mawhound-rig.js';
function source(){const b=readFileSync(new URL('../assets/models/Mawhound.glb',import.meta.url));const len=b.readUInt32LE(12),j=JSON.parse(b.toString('utf8',20,20+len));const data=20+len+8,g=new T.BufferGeometry();for(const [name,index,width] of [['position',0,3]]){const a=j.accessors[index],v=j.bufferViews[a.bufferView],start=data+(v.byteOffset||0)+(a.byteOffset||0);const copy=b.buffer.slice(b.byteOffset+start,b.byteOffset+start+a.count*width*4);g.setAttribute(name,new T.Float32BufferAttribute(new Float32Array(copy),width));}const a=j.accessors[1],v=j.bufferViews[a.bufferView],start=data+(v.byteOffset||0)+(a.byteOffset||0);g.setIndex(new T.Uint32BufferAttribute(new Uint32Array(b.buffer.slice(b.byteOffset+start,b.byteOffset+start+a.count*4)),1));return g;}
test('Mawhound skin has normalized weights, finite normals and eight working clips',()=>{const {mesh,clips}=rigMawhound(source(),new T.MeshBasicMaterial());assert.equal(mesh.skeleton.bones.length,17);assert.equal(clips.length,8);const g=mesh.geometry,w=g.attributes.skinWeight;for(let i=0;i<w.count;i++){const weights=[w.getX(i),w.getY(i),w.getZ(i),w.getW(i)];assert.ok(weights.every(v=>Number.isFinite(v)&&v>=0));assert.ok(Math.abs(weights.reduce((a,b)=>a+b,0)-1)<1e-6);}assert.ok([...g.attributes.normal.array].every(Number.isFinite));const mixer=new T.AnimationMixer(mesh);for(const clip of clips){mixer.stopAllAction();mixer.clipAction(clip).reset().play();mixer.update(.6);mesh.updateMatrixWorld(true);mesh.skeleton.update();let moved=0;for(let i=0;i<g.attributes.position.count;i+=101){const p=new T.Vector3().fromBufferAttribute(g.attributes.position,i),q=mesh.applyBoneTransform(i,p.clone());assert.ok(q.toArray().every(Number.isFinite));if(p.distanceTo(q)>1e-5)moved++;}assert.ok(moved>10,clip.name+' must actually deform the skin');}});

test('walk moves all four paws and closes its loop; standing plants the rear paws',()=>{
 const {mesh,clips}=rigMawhound(source(),new T.MeshBasicMaterial()),mixer=new T.AnimationMixer(mesh),bones=mesh.skeleton.bones;
 const paws=bones.filter(b=>b.name.endsWith('Paw'));assert.equal(paws.length,4);mesh.updateMatrixWorld(true);const rest=paws.map(p=>p.getWorldPosition(new T.Vector3()));
 const walk=clips.find(c=>c.name==='Walking');for(const track of walk.tracks){const width=track.getValueSize();for(let i=0;i<width;i++)assert.ok(Math.abs(track.values[i]-track.values[track.values.length-width+i])<1e-5,'walk seam: '+track.name);}
 const action=mixer.clipAction(walk).play();mixer.update(.2);mesh.updateMatrixWorld(true);paws.forEach((p,i)=>assert.ok(p.getWorldPosition(new T.Vector3()).distanceTo(rest[i])>.015,p.name+' should step'));
 action.stop();mixer.clipAction(clips.find(c=>c.name==='Rear-leg stand')).play();mixer.update(2);mesh.updateMatrixWorld(true);
 paws.forEach((p,i)=>{const position=p.getWorldPosition(new T.Vector3());if(p.name.startsWith('Rear'))assert.ok(position.distanceTo(rest[i])<1e-6,p.name+' should remain planted');else assert.ok(position.y-rest[i].y>.4,p.name+' should be lifted');});
});
test('exported GLB includes all 17 joints and eight valid named animations',()=>{const file=readFileSync(new URL('../assets/models/Mawhound-game.glb',import.meta.url)),j=JSON.parse(file.toString('utf8',20,20+file.readUInt32LE(12)));assert.equal(file.readUInt32LE(8),file.length);assert.equal(j.skins[0].joints.length,17);assert.deepEqual(j.animations.map(a=>a.name),['Idle breathing','Walking','Rear-leg stand','Play bow','Curious head tilt','Happy greeting','Sniff around','Shake off']);for(const clip of j.animations)for(const channel of clip.channels){assert.ok(j.skins[0].joints.includes(channel.target.node));assert.ok(['translation','rotation','scale'].includes(channel.target.path));}});

test('upright head faces forward in the asset and tracks the camera in world space',async()=>{
 const {aimMawhoundHead}=await import('../mawhound-look.js');const {mesh,clips}=rigMawhound(source(),new T.MeshBasicMaterial());const mixer=new T.AnimationMixer(mesh);mixer.clipAction(clips.find(c=>c.name==='Rear-leg stand')).play();mixer.update(2);mesh.updateMatrixWorld(true);const head=mesh.getObjectByName('MawHead'),q=new T.Quaternion();head.getWorldQuaternion(q);assert.ok(new T.Vector3(0,0,1).applyQuaternion(q).z>.99);
 const target=new T.Vector3(.4,1.2,3);aimMawhoundHead(head,target);head.getWorldQuaternion(q);const actual=new T.Vector3(0,0,1).applyQuaternion(q),expected=target.clone().sub(head.getWorldPosition(new T.Vector3())).normalize();assert.ok(actual.dot(expected)>.999);
});
